# syntax=docker/dockerfile:1
FROM python:3.12.9-slim-bookworm
WORKDIR /app
COPY services/python/requirements.txt .
RUN --mount=type=secret,id=proxy_ca if [ -f /run/secrets/proxy_ca ]; then export PIP_CERT=/run/secrets/proxy_ca; fi; pip install --no-cache-dir -r requirements.txt
COPY tools /app/tools
CMD ["python", "-m", "tools.downstream"]
